name: E2E Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  chrome:

    runs-on: ubuntu-latest

    steps:
    - name: Get code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.13.5"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        pip install -r requirements.txt

    - name: Run E2E Tests
      run: robot -d ./logs tests

    - name: Robot reporter
      uses: joonvena/robotframework-reporter-action@v2.4
      if: always()
      with:
        gh_access_token: ${{ secrets.GITHUB_TOKEN }}
        report_path: logs
    
    - name: Upload Report
      uses: actions/upload-artifact@v4.6.2
      if: always()
      with:
        name: Chrome tests report
        path: logs
